models:
    image: tp33/django
    external_links:
        - mysql:db
    ports:
        - "8001:8000"
    volumes:
        - ~/cs4501/entity:/app
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata db.json && mod_wsgi-express start-server --reload-on-changes wiz/wsgi.py" 

exp:
    image: tp33/django
    links:
        - models:models-api
    ports:
        - "8002:8000"
    volumes:
        - ~/cs4501/experience:/app
    command: bash -c "pip install requests && mod_wsgi-express start-server --reload-on-changes experience/wsgi.py"

web:
    image: tp33/django
    links:
        - exp:exp-api
    ports:
        - "8000:8000"
    volumes:
        - ~/cs4501/frontend:/app
    command: bash -c "pip install requests && mod_wsgi-express start-server --reload-on-changes frontend/wsgi.py"

